# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 13.2.1
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
          name: Build and Run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: gigup
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output

workflows:
  version: 2
  build-test-test:
    jobs:
      - build-and-test
